### ISSUE TITLE
Implementing Ord?

### ISSUE THREAD

**Issue by phhusson** [dholroyd/rtp-rs#3]
I'm wondering would it make sense to implement Ord, and not just PartialOrd?

Considering the thing is currently implemented, it is possible to implement a full ordering, since sub will never return 0 for different sequence numbers.

My usecase for this would be re-order and de-duplicate packets using a BTreeMap, which require Ord.

**Comment by dholroyd** [comment]
Does it pose any problems for your usecase that `PartialOrd` impl violates transitivity (required by [the trait](https://doc.rust-lang.org/std/cmp/trait.PartialOrd.html) - "_The comparison must satisfy, for all a, b and c ... transitivity: `a < b` and `b < c` implies `a < c`_".)

Given `PartialOrd` is there, adding `Ord` doesn't seem to make this existing problem worse, so I'd be happy to add that for now.

Would be nice to do better in future.

**Comment by phhusson** [comment]
Yeah, I know transivity is broken, but it's already broken in PartialOrd anyway.

For the use-case of re-orderning packets, doing FEC correction or retransmission, you never need more than 4096 contiguous packets (that's roughly 4s on usual streams, that's way too much for the user anyway), so between pkt i and pkt (i+4096)%65536, your current ordening guarantees transitivity

So it should be okay for all the use-cases I listed.

Sure, don't use that for timeshift :-)
